
TYPE
	HERNON_Dispense_Enum : 
		(
		DISPENSE_STATE_INIT := 0,
		DISPENSE_STATE_READY := 1,
		DISPENSE_STATE_DISPENSING := 2,
		DISPENSE_STATE_WAIT_RESET := 3,
		DISPENSE_STATE_DISABLED := 4,
		DISPENSE_STATE_ERROR := 5,
		DISPENSE_STATE_WAIT_VALVE := 6,
		DISPENSE_STATE_WAIT_ADDITIONAL := 7,
		DISPENSE_STATE_MANUAL := 8
		);
END_TYPE
