
TYPE
	CMA_Arimat_PrcsState_Enum : 
		(
		PRCS_STATE_INIT,
		PRCS_STATE_IDLE,
		PRCS_STATE_WAIT_LOADER,
		PRCS_STATE_FEED_OFFSET,
		PRCS_STATE_BLADE_CREASER,
		PROCESS_STATE_FINISHING,
		PROCESS_STATE_ERROR
		);
	CMA_Arimat_MachineState_Enum : 
		(
		MACHINE_STATE_INIT,
		MACHINE_STATE_IDLE,
		MACHINE_STATE_RUNNING,
		MACHINE_STATE_ERRORSTOP,
		MACHINE_STATE_MANUAL_CTRL
		);
END_TYPE
