/* Automation Studio generated header file */
/* Do not edit ! */

#ifndef _LIBRARIES_20170412152430_
#define _LIBRARIES_20170412152430_

__asm__(".section \".plc\"");

/* Used IEC files */
__asm__(".ascii \"iecfile \\\"Logical/Libraries/operator/operator.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/runtime/runtime.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/astime/astime.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIecCon/AsIecCon.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsXml/AsXml.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/standard/standard.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/brsystem/brsystem.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/sys_lib/sys_lib.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsANSL/AsANSL.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsARCfg/AsARCfg.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrMath/AsBrMath.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrStr/AsBrStr.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/DataObj/DataObj.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsTCP/AsTCP.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsUDP/AsUDP.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsUSB/AsUSB.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArSdm/AsArSdm.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIOTime/AsIOTime.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsMem/AsMem.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArLog/AsArLog.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArProf/AsArProf.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MTTypes/MTTypes.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/jgLibC/Types.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MTData/MTData.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/wbrServices/wbrMemSvc/wbrMemSvc.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/wbrServices/wbrListSvc/wbrListSvc.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/wbrServices/wbrLogSvc/wbrLogSvc.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/wbrServices/bglibasWBR/bglibasWBR.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsICMP/AsICMP.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpCom/MpCom.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpCom/MpComError.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpRecipe/MpRecipe.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpRecipe/MpRecipeAlarm.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpRecipe/MpRecipeError.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpAlarm/MpAlarmError.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpAlarm/MpAlarm.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpFile/MpFile.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpFile/MpFileError.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpFile/MpFileAlarm.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/NcGlobal/NcGlobal.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/ArTextSys/ArTextSys.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MAPPSuppor/MAPPSuppor.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MAPPSuppor/HMIparamList.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/wbrServices/wbrPingSvc/wbrPingSvc.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10man/Acp10man.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10_MC/acp10_mc.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10sim/acp10sim.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpAxis/MpAxis.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpAxis/MpAxisError.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpAxis/MpAxisAlarm.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/operator/operator.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/runtime/runtime.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/astime/astime.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIecCon/AsIecCon.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsXml/AsXml.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/standard/standard.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/brsystem/brsystem.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/sys_lib/sys_lib.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsANSL/AsANSL.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsARCfg/AsARCfg.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrMath/AsBrMath.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrStr/AsBrStr.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/DataObj/DataObj.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsTCP/AsTCP.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsUDP/AsUDP.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsUSB/AsUSB.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArSdm/AsArSdm.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIOTime/AsIOTime.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsMem/AsMem.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArLog/AsArLog.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArProf/AsArProf.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MTTypes/MTTypes.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/jgLibC/jgLibC.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MTData/MTData.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/wbrServices/wbrMemSvc/wbrMemSvc.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/wbrServices/wbrListSvc/wbrListSvc.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/wbrServices/wbrLogSvc/wbrLogSvc.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/wbrServices/bglibasWBR/bglibasWBR.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/wbrServices/wbrSvcUtilities/wbrFltUtil/wbrFltUtil.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsICMP/AsICMP.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpCom/MpCom.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpWebXs/MpWebXs.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpRecipe/MpRecipe.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpAlarm/MpAlarm.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpFile/MpFile.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/NcGlobal/NcGlobal.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/ArTextSys/ArTextSys.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MAPPSuppor/MAPPSuppor.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/wbrServices/wbrPingSvc/wbrPingSvc.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10_MC/acp10_mc.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpAxis/MpAxis.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/operator/operator.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/runtime/runtime.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/astime/astime.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIecCon/AsIecCon.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsXml/AsXml.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/standard/standard.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/brsystem/brsystem.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/sys_lib/sys_lib.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsANSL/AsANSL.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsARCfg/AsARCfg.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrMath/AsBrMath.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrStr/AsBrStr.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/DataObj/DataObj.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsTCP/AsTCP.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsUDP/AsUDP.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsUSB/AsUSB.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArSdm/AsArSdm.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIOTime/AsIOTime.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsMem/AsMem.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArLog/AsArLog.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArProf/AsArProf.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MTTypes/MTTypes.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/jgLibC/Constants.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MTData/MTData.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/wbrServices/wbrListSvc/wbrListSvc.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/wbrServices/wbrLogSvc/wbrLogSvc.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/wbrServices/bglibasWBR/bglibasWBR.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsICMP/AsICMP.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpCom/MpCom.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10par/Acp10par.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/NcGlobal/NcGlobal.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/ArTextSys/ArTextSys.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MAPPSuppor/MAPPSuppor.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10_MC/acp10_mc.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10sim/acp10sim.var\\\" scope \\\"global\\\"\\n\"");

/* Exported library functions and function blocks */
#ifdef _OPERATOR_EXPORT
	__asm__(".ascii\"plcexport \\\"SIZEOF\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ADR\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ADRINST\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SHR\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ROR\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ROL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SHL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"AND\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"XOR\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"OR\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"NOT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ADD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MUL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SUB\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DIV\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MOVE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MAX\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MIN\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LIMIT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SEL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MUX\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"GE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"EQ\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"GT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"NE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ABS\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SQRT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LN\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LOG\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"EXP\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SIN\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"COS\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TAN\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ASIN\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ACOS\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ATAN\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"EXPT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TRUNC\\\" FUN\\n\"");
#endif
#ifdef _RUNTIME_EXPORT
	__asm__(".ascii\"plcexport \\\"r_trig\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"f_trig\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"rf_trig\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"GetTime\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SFCActionControl\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"SFCAC2\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"RealTan\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RealAtan\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RealAsin\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RealAcos\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RealExp\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RealLn\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RealLog\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RealExpt\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RealAbs\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RealSin\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RealCos\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RealSqrt\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SFCAC3\\\" FUB\\n\"");
#endif
#ifdef _ASTIME_EXPORT
	__asm__(".ascii\"plcexport \\\"DTExSetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DTSetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DTGetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"clock_ms\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UtcDTGetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UtcDTSetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UtcDTExSetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DTStructureGetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DTStructureSetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DTStructureExSetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UtcDTStructureGetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UtcDTStructureSetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UtcDTStructureExSetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UtcDT_TO_LocalDTStructure\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LocalDT_TO_UtcDTStructure\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UtcDTStructure_TO_LocalDT\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LocalDTStructure_TO_UtcDT\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"ascTIMEStructure\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ascDTStructure\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ascTIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ascDT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIMEStructure_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_TIMEStructure\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DTStructure_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_DTStructure\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DiffT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DiffDT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TimeDeviceGetInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DstGetInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DstGetInfoDT\\\" FUB\\n\"");
#endif
#ifdef _ASIECCON_EXPORT
	__asm__(".ascii\"plcexport \\\"swapDT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"swapTIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"swapDATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"swapTOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"swapREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"swapLREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"swapUDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"swapDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"swapUINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"swapINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"swapWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"swapDWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"N_TO_HDT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"N_TO_HTIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"N_TO_HDATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"N_TO_HTOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"N_TO_HREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"N_TO_HLREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"N_TO_HUDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"N_TO_HDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"N_TO_HUINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"N_TO_HINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"H_TO_NDT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"H_TO_NTIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"H_TO_NDATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"H_TO_NTOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"H_TO_NREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"H_TO_NLREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"H_TO_NUDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"H_TO_NDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"H_TO_NUINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"H_TO_NINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_STRING\\\" FUN\\n\"");
#endif
#ifdef _FILEIO_EXPORT
	__asm__(".ascii\"plcexport \\\"FileCreate\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileOpen\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileClose\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileRead\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileReadEx\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileWrite\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileWriteEx\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileRename\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileCopy\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileDelete\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileTruncate\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DirCreate\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DirOpen\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DirClose\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DirRead\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DirReadEx\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DirInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DirRename\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DirCopy\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DirDelete\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DirDeleteEx\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"SetAttributes\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"GetAttributes\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DevMemInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DevLink\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DevUnlink\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"GetVolumeLabel\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"GetVolumeSerialNo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileIoGetSysError\\\" FUN\\n\"");
#endif
#ifdef _ASXML_EXPORT
	__asm__(".ascii\"plcexport \\\"xmlCreateMemoryReader\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"xmlCloseMemoryReader\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"xmlReadNextNode\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"xmlReadAttributeNr\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"xmlCreateMemoryWriter\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"xmlGetMemoryInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"xmlCloseMemoryWriter\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"xmlWriteStartDocument\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"xmlWriteStartDocEnc\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"xmlWriteEndDocument\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"xmlWriteStartElement\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"xmlWriteAttribute\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"xmlWriteElementText\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"xmlWriteElementTextEx\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"xmlWriteEndElement\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"xmlWriteComment\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"xmlWriteCommentEx\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"xmlWriteCData\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"xmlWriteCDataEx\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"xmlWritePI\\\" FUB\\n\"");
#endif
#ifdef _STANDARD_EXPORT
	__asm__(".ascii\"plcexport \\\"RF_TRIG\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CTUD\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CTD\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CTU\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"F_TRIG\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"R_TRIG\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"SR\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"RS\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"SEMA\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"TON\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"TOF\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"TP\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"TON_10ms\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"TOF_10ms\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"TP_10ms\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LEN\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LEFT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RIGHT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MID\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"CONCAT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INSERT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DELETE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REPLACE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"FIND\\\" FUN\\n\"");
#endif
#ifdef _BRSYSTEM_EXPORT
	__asm__(".ascii\"plcexport \\\"MEMInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MEMxInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"SysInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"RTInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"TARGETInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"HWInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"SysconfInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"SysconfSet\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"BatteryInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"EXCInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"ZYKVLenable\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"PMemGet\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"PMemPut\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"PMemSize\\\" FUB\\n\"");
#endif
#ifdef _SYS_LIB_EXPORT
	__asm__(".ascii\"plcexport \\\"Byte2Bit\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"Bit2Byte\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"KEY_read\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"KEY_enadis\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DA_fix\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DA_info\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DA_copy\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DA_store\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DA_burn\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DA_delete\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DA_ident\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DA_read\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DA_write\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DA_create\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DIS_clr\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DIS_chr\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DIS_str\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ERRxfatal\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ERR_read\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ERRxread\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ERR_fatal\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ERR_warning\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ERRxwarning\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SM_release\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SM_attach\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SM_delete\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SM_ident\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SM_create\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIM_ticks\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIM_musec\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SW_settime\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SW_gettime\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RTC_settime\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RTC_gettime\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TMP_free\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TMP_alloc\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MEM_free\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MEM_alloc\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"AVT_info\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"AVT_release\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"AVT_attach\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"AVT_ident\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"AVT_cancel\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"AVT_create\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UT_sleep\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UT_exit\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UT_freemsg\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UT_recmsg\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UT_sendmsg\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UT_resume\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UT_suspend\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UT_ident\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ST_name\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ST_info\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ST_allsuspend\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ST_tmp_resume\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ST_tmp_suspend\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ST_resume\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ST_suspend\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ST_ident\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"FORCE_info\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MO_ver\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MO_list\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MO_info\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"SYS_battery\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SYSreset\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SYSxinfo\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SYS_info\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_xlist\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_ninfo\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_item\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_ident\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_list\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_info\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_xgetval\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_xsetval\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_xgetadr\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_getadr\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_getval\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_setval\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"slMoList\\\" FUB\\n\"");
#endif
#ifdef _ASANSL_EXPORT
	__asm__(".ascii\"plcexport \\\"AsANSLClientStart\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsANSLClientStop\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsANSLClientDiag\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsANSLClientDiagAll\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsANSLClientDiagConn\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsANSLClientDiagConnAll\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsANSLClientDiagRedConn\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsANSLClientDiagPv\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsANSLClientDiagPvAll\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsANSLServerRRInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsANSLServerConnCount\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"AsANSLServerDiagConnAll\\\" FUB\\n\"");
#endif
#ifdef _ASARCFG_EXPORT
	__asm__(".ascii\"plcexport \\\"CfgGetInaNode\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetInaNode\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetIPAddr\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetIPAddr\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetSubnetMask\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetSubnetMask\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetClusterIPAddr\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetClusterIPAddr\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetDefaultGateway\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetDefaultGateway\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetBroadcastAddr\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetBroadcastAddr\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetEthBaudrate\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetEthBaudrate\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetEthConfigMode\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetEthConfigMode\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetHostName\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetHostName\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetHostNameIf\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetHostNameIf\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetMacAddr\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetFTPServer\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetTimeOffset\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetTimeOffset\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetSntpServer\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetSntpClient\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetSntpcData\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetSntpsData\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetNtpServer\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetNtpsData\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetNtpClient\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetNtpcData\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetTimeZone\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetTimeZone\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetTimeZoneInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetTimeZoneEntry\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetDst\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetDst\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetCIFSDomain\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetCIFSDomain\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetCIFSDefaultuser\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetCIFSDefaultuser\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetDhcpServer\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetDhcpsData\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetDhcpsData\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetSdmStatus\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetSdmStatus\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgClearNV\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetSdmColor\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetSdmColor\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetSdmCustomData1\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetSdmCustomData1\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetSdmCustomData2\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetSdmCustomData2\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetWebMimeType\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetWebMimeType\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetWebServerHttpsConfig\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetWebServerPort\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetWebServerDevice\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetWebAspGoform\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetWebAspGoform\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetWebServerStatus\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetWebServerStatus\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetDnsMode\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetDnsMode\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetDnsSuffix\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetDnsSuffix\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgGetDnsAddress\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CfgSetDnsAddress\\\" FUB\\n\"");
#endif
#ifdef _ASBRMATH_EXPORT
	__asm__(".ascii\"plcexport \\\"brmatan2\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brmceil\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brmcosh\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brmfloor\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brmfmod\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brmfrexp\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brmldexp\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brmmodf\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brmpow\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brmsinh\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brmtanh\\\" FUN\\n\"");
#endif
#ifdef _ASBRSTR_EXPORT
	__asm__(".ascii\"plcexport \\\"brsftoa\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brsatof\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brsatod\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brsitoa\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brsatoi\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brsmemset\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brsmemcpy\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brsmemmove\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brsmemcmp\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brsstrcat\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brsstrlen\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brsstrcpy\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brsstrcmp\\\" FUN\\n\"");
#endif
#ifdef _DATAOBJ_EXPORT
	__asm__(".ascii\"plcexport \\\"DatObjCreate\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DatObjWrite\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DatObjRead\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DatObjDelete\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DatObjMove\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DatObjCopy\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DatObjInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DatObjChangeDate\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DatObjAttach\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DatObjDetach\\\" FUB\\n\"");
#endif
#ifdef _ASTCP_EXPORT
	__asm__(".ascii\"plcexport \\\"TcpOpen\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"TcpOpenSsl\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"TcpServer\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"TcpClient\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"TcpClose\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"TcpSend\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"TcpRecv\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"TcpIoctl\\\" FUB\\n\"");
#endif
#ifdef _ASUDP_EXPORT
	__asm__(".ascii\"plcexport \\\"UdpOpen\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UdpClose\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UdpConnect\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UdpDisconnect\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UdpSend\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UdpRecv\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UdpIoctl\\\" FUB\\n\"");
#endif
#ifdef _ASUSB_EXPORT
	__asm__(".ascii\"plcexport \\\"UsbNodeListGet\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UsbNodeGet\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UsbDescriptorGet\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UsbMsDeviceReady\\\" FUB\\n\"");
#endif
#ifdef _ASARSDM_EXPORT
	__asm__(".ascii\"plcexport \\\"SdmSystemDump\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"SdmSetAppParam\\\" FUB\\n\"");
#endif
#ifdef _ASIOTIME_EXPORT
	__asm__(".ascii\"plcexport \\\"AsIOTimeStamp\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"AsIOTimeCyclicStart\\\" FUN\\n\"");
#endif
#ifdef _ASMEM_EXPORT
	__asm__(".ascii\"plcexport \\\"AsMemPartCreate\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsMemPartDestroy\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsMemPartAlloc\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsMemPartAllocClear\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsMemPartRealloc\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsMemPartFree\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsMemPartInfo\\\" FUB\\n\"");
#endif
#ifdef _ASARLOG_EXPORT
	__asm__(".ascii\"plcexport \\\"AsArLogCreate\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsArLogDelete\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsArLogWrite\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsArLogRead\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsArLogClear\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsArLogGetInfo\\\" FUB\\n\"");
#endif
#ifdef _ASARPROF_EXPORT
	__asm__(".ascii\"plcexport \\\"LogInstall\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LogDeInstall\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LogStateGet\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LogArchCreate\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LogArchDelete\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LogArchCopy\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LogArchInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LogStart\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LogStop\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LogEvent\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LogIdleShow\\\" FUB\\n\"");
#endif
#ifdef _JGLIBC_EXPORT
	__asm__(".ascii\"plcexport \\\"Tms\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"Debounce_Signal\\\" FUB\\n\"");
#endif
#ifdef _MTDATA_EXPORT
	__asm__(".ascii\"plcexport \\\"MTDataStdDeviation\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MTDataVariance\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MTDataRMS\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MTDataMean\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MTDataMinMax\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MTDataStatistics\\\" FUB\\n\"");
#endif
#ifdef _WBRMEMSVC_EXPORT
	__asm__(".ascii\"plcexport \\\"initMemSvc\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"memSvcAllocate\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"memSvcFree\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"memSvcGetMemInfo\\\" FUN\\n\"");
#endif
#ifdef _WBRLISTSVC_EXPORT
	__asm__(".ascii\"plcexport \\\"listSvcRequestListNode\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"listSvcRequestList\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"initListSvc\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"listSvcDeleteCurrentNode\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"listSvcGetHeadData\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"listSvcGetCurrNodeData\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"listSvcGetLastNodeData\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"listSvcGoNextNodeAndGetData\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"listSvcCharListToStringArray\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"listCurrentEntries\\\" FUN\\n\"");
#endif
#ifdef _WBRLOGSVC_EXPORT
	__asm__(".ascii\"plcexport \\\"setLogServiceDataAddress\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"initLogService\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"requestMessageToLog\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"requestInfoMsgToLogbookNoData\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"requestMessageToLogDefault\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"writeMessagesToLog\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"getLogbookInfo\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"createNewLogbook\\\" FUN\\n\"");
#endif
#ifdef _BGLIBASWBR_EXPORT
	__asm__(".ascii\"plcexport \\\"bgSSMInitWbr\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgSSMInit\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgSSMCyclic\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgSSMStateNextWithWatchdog\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgSSMStateNextTimeDelay\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgSSMStateNextCycleDelay\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgSSMStateAfterSub\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgSSMReturnFromSub\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgSSMStateNext\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgSSMIsStateInit\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgSSMPrintLogMessage\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgSSMPrintToTextLogIEC\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgSSMPrintLogMessageToLogbook\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgSSMPrintToLogbookIEC\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgSSMGetState\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgSSMGetStateText\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgFIFOInit\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgFIFOPush\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgFIFOPull\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgFIFOGetCount\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgFIFOIsFull\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgTimerOffCyclic\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgTimerCyclic\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgTimerStart\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgTimerStop\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgTimerIsEnabled\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgTimerIsTimeOut\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgTimerTimeElapsed\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"bgTimerTimeRemaining\\\" FUN\\n\"");
#endif
#ifdef _WBRFLTUTIL_EXPORT
	__asm__(".ascii\"plcexport \\\"wbrDoubleInRange\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"wbrDoubleCompare\\\" FUN\\n\"");
#endif
#ifdef _ASICMP_EXPORT
	__asm__(".ascii\"plcexport \\\"IcmpPing\\\" FUB\\n\"");
#endif
#ifdef _MPCOM_EXPORT
	__asm__(".ascii\"plcexport \\\"MpComConfigManager\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MpComLoggerUI\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MpComHandle\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MpComVersion\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MpComLink\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MpComLinkToParent\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MpComDump\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MpComGetLink\\\" FUB\\n\"");
#endif
#ifdef _MPRECIPE_EXPORT
	__asm__(".ascii\"plcexport \\\"MpRecipeRegParSync\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MpRecipeRegPar\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MpRecipeXml\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MpRecipeUI\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MpRecipeCsv\\\" FUB\\n\"");
#endif
#ifdef _MPALARM_EXPORT
	__asm__(".ascii\"plcexport \\\"MpAlarmBasic\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MpAlarmBasicUI\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MpAlarmReaction\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MpAlarmSet\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MpAlarmReset\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MpAlarmRegUser\\\" FUB\\n\"");
#endif
#ifdef _MPFILE_EXPORT
	__asm__(".ascii\"plcexport \\\"MpFileManagerUI\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MpFileManagerConfig\\\" FUB\\n\"");
#endif
#ifdef _NCGLOBAL_EXPORT
	__asm__(".ascii\"plcexport \\\"nccnccom\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ncda_dir\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ncda_inf\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ncda_id\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ncda_wr\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ncda_cr\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ncaccess\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ncalloc\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ncaction\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ncglobal_action\\\" FUN\\n\"");
#endif
#ifdef _ARTEXTSYS_EXPORT
	__asm__(".ascii\"plcexport \\\"ArTextSysGetSystemLanguage\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"ArTextSysSetSystemLanguage\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"ArTextSysGetNamespaceLanguages\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"ArTextSysGetText\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"ArTextSysFormatString\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"ArTextSysGetFormattedText\\\" FUB\\n\"");
#endif
#ifdef _MAPPSUPPOR_EXPORT
	__asm__(".ascii\"plcexport \\\"hmiParamListTableCyclic\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"FBK_Init_Logbook\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"hmiTableFBK_typ\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"ActivateHMITable\\\" FUN\\n\"");
#endif
#ifdef _WBRPINGSVC_EXPORT
	__asm__(".ascii\"plcexport \\\"wbrPingSvcInit\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"wbrPingStation\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"wbrSQL_DT2_ISOFmtdStringFromDT\\\" FUN\\n\"");
#endif
#ifdef _ACP10_MC_EXPORT
	__asm__(".ascii\"plcexport \\\"MC_AbortTrigger\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_AutCommand\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_AutControl\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_AutoCamDwell\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_AxisErrorCollector\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_BrakeControl\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_BrakeOperation\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CalcCamFromPoints\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CalcCamFromSections\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CalcPointsFromCam\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CalcSectionsFromCam\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CamIn\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CamDwell\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CamTransition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CheckAutCompensation\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CheckEndlessPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CommandError\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ConfigPowerStageCheck\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CrossCutterControl\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CyclicRead\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CyclicReadDataInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CyclicWrite\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_DigitalCamSwitch\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_DownloadCamProfileObj\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_DownloadCamProfileData\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_DownloadParSequ\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_EventMoveAbsolute\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_EventMoveAdditive\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_EventMoveVelocity\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_GearIn\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_GetCamMasterPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_GetCamSlavePosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_GetErrorText\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_GetHardwareInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_GetParIDTransferInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_HomeAcpEncoder\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitAutData\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitAutEvent\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitAutPar\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitAutState\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitAxisPar\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitAxisSubjectPar\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitCyclicRead\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitCyclicWrite\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitEndlessPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitEndlessPosAcpEnc\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitMasterParIDTransfer\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitModPos\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitParList\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitParSequ\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitParTabObj\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitReceiveNetworkData\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitReceiveNetworkEnc\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitReceiveParID\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitSendParID\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_JogVelocity\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_JogLimitPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_JogTargetPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_LimitLoad\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_LimitLoadCam\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_LoadAxisPar\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_MoveAbsoluteTriggStop\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_MoveAdditiveTriggStop\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_MoveCyclicPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_MoveCyclicPositionExt\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_MoveCyclicVelocity\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_MoveCyclicVelocityExt\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_MoveVelocityTriggStop\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_NetTrace\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_NetworkInit\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_Offset\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_OffsetVelocity\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_OffsetZone\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_GetParIDInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ParTrace\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ParTraceConfig\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_Phasing\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_MechPosDeviationComp\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_PowerMeter\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ReadAutPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ReadAxisError\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ReadCyclicPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ReadDriveStatus\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ReadNetTraceStatus\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ReadParID\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ReadParIDText\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ReadParList\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ReadParTraceStatus\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ReceiveParIDOnPLC\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ResetAutPar\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_SaveAxisPar\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_SaveCamProfileObj\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_SetHardwareInputs\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_SetupController\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_SetupFromParTabObj\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_SetupInductionMotor\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_SetupIsqRipple\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_SetupMotorPhasing\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_SetupSynchronMotor\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_Simulation\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_TouchProbe\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_VelocityControl\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_WriteParID\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_WriteParIDText\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_CamIn\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_CamOut\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_CamTableSelect\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_DigitalCamSwitch\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_GearIn\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_GearInPos\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_GearOut\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_Halt\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_Home\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_LimitLoad\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_MoveAbsolute\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_MoveAdditive\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_MoveVelocity\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_Phasing\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_Power\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_ReadActualPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_ReadActualTorque\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_ReadActualVelocity\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_ReadAxisError\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_ReadBoolParameter\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_ReadDigitalInput\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_ReadDigitalOutput\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_ReadParameter\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_ReadStatus\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_Reset\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_SetOverride\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_Stop\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_TouchProbe\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_TorqueControl\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_TorqueControl\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_WriteBoolParameter\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_WriteDigitalOutput\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_WriteParameter\\\" FUB\\n\"");
#endif
#ifdef _MPAXIS_EXPORT
	__asm__(".ascii\"plcexport \\\"MpAxisBasic\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MpAxisCamSequencer\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MpAxisCoupling\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MpAxisCyclicSet\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MpAxisBasicConfig\\\" FUB\\n\"");
#endif

__asm__(".previous");


#endif /* _LIBRARIES_20170412152430_ */

