#ifndef _DEFAULT_757602046
#define _DEFAULT_757602046
#include <bur/plctypes.h>
#include <bur/plc.h>

#ifdef __cplusplus 
extern "C" 
{
#endif
	#include <operator.h>
	#include <runtime.h>
	#include <astime.h>
	#include <AsIecCon.h>
	#include <FileIO.h>
	#include <AsXml.h>
	#include <standard.h>
	#include <brsystem.h>
	#include <sys_lib.h>
	#include <AsANSL.h>
	#include <AsARCfg.h>
	#include <AsBrMath.h>
	#include <AsBrStr.h>
	#include <DataObj.h>
	#include <AsTCP.h>
	#include <AsUDP.h>
	#include <AsUSB.h>
	#include <AsArSdm.h>
	#include <AsIOTime.h>
	#include <AsMem.h>
	#include <AsArLog.h>
	#include <AsArProf.h>
	#include <MTTypes.h>
	#include <jgLibC.h>
	#include <MTData.h>
	#include <wbrMemSvc.h>
	#include <wbrListSvc.h>
	#include <wbrLogSvc.h>
	#include <bglibasWBR.h>
	#include <wbrFltUtil.h>
	#include <AsICMP.h>
	#include <MpCom.h>
	#include <MpWebXs.h>
	#include <MpRecipe.h>
	#include <MpAlarm.h>
	#include <MpFile.h>
	#include <Acp10par.h>
	#include <NcGlobal.h>
	#include <ArTextSys.h>
	#include <MAPPSuppor.h>
	#include <wbrPingSvc.h>
	#include <Acp10man.h>
	#include <Acp10_MC.h>
	#include <Acp10sim.h>
	#include <MpAxis.h>
#ifdef __cplusplus
};
#endif

#include <mpcomponentsVAR.h>
#include <globalVAR.h>
#include <machineTYP.h>
#include <generic_rec_cfgTYP.h>
#include <libraries/wbrservices/wbrservicesTYP.h>
#include <libraries/wbrservices/wbrservicesglobalVAR.h>
#include <libraries/wbrservices/timerservices/timerservicesTYP.h>
#include <libraries/wbrservices/timerservices/timerservicesVAR.h>
#include <auxiliary_services_control/usb_mount_typesTYP.h>
#include <auxiliary_services_control/auxiliaryVAR.h>
#include <hmi/generic_controlsTYP.h>
#include <hmi/hmi_pagesTYP.h>
#include <hmi/hmidialogTYP.h>
#include <hmi/hmimsgscrollTYP.h>
#include <hmi/hmiforceioTYP.h>
#include <hmi/hmialertTYP.h>
#include <hmi/hmiTYP.h>
#include <hmi/hmiremmemTYP.h>
#include <hmi/hmiVAR.h>
#include <motioncontrol/motionvarVAR.h>
#endif
