
TYPE
	HERNON_Inspect_Enum : 
		(
		INSPECT_STATE_INIT := 0,
		INSPECT_STATE_READY := 1,
		INSPECT_STATE_WAIT_RESULTS := 2,
		INSPECT_STATE_ERROR := 3,
		INSPECT_STATE_DISABLED := 4,
		INSPECT_STATE_WAIT_TRIG := 5,
		INSPECT_STATE_WAIT_BUSY := 6,
		INSPECT_STATE_WAIT_VBLOCK_DISP := 7,
		INSPECT_STATE_MANUAL := 8
		);
	HERNON_Inspect_Unit_ID_Enum : 
		(
		INSPECT_PRIMER := 0,
		INSPECT_MOUTH := 1
		);
	HERNON_Inspection_Outcome_Enum : 
		(
		INSPECTION_RESULTS_NONESOFAR := 0,
		INSPECTION_RESULTS_GOOD := 1,
		INSPECTION_RESULTS_BAD := 2,
		INSPECTION_RESULTS_ERROR := 3,
		INSPECTION_NA_EMPTY_VBLOCK := 4,
		INSPECTION_ERROR_ALREADY_DONE := 5
		);
END_TYPE
