
TYPE
	HERNON_Dispense_Enum : 
		(
		DISPENSE_STATE_INIT := 0,
		DISPENSE_STATE_READY := 1,
		DISPENSE_STATE_DISPENSING := 2,
		DISPENSE_STATE_WAIT_RESET := 3,
		DISPENSE_STATE_INACTIVE := 4,
		DISPENSE_STATE_DISABLED := 5,
		DISPENSE_STATE_ERROR := 6,
		DISPENSE_STATE_WAIT_ADDITIONAL := 8,
		STATE_WAIT_FRACTION_OFFSET := 9
		);
	HERNON_DISP_REASONS_ENUM : 
		(
		DISPENSE_SINGLE_SHOT := 0,
		DISPENSE_PURGE := 1
		);
END_TYPE
