(********************************************************************
 * COPYRIGHT -- Bernecker + Rainer
 ********************************************************************
 * Library: MTBasics
 * File: MTBasics.typ
 * Author: B&R
 ********************************************************************
 * Data types of library MTBasics
 * User area of error/warning codes: 36250 - 36349
 ********************************************************************)

TYPE
	MTBasicsPIDParameterType : 	STRUCT  (*PID parameters.*)
		Gain : REAL; (*Proportional gain. Valid value range: Gain > 0.*)
		IntegrationTime : REAL; (*Integral time constant for the integral component. Unit: [s]. Valid value range: IntegrationTime >= 0.*)
		DerivativeTime : REAL; (*Differential time constant for the derivative component. Unit: [s]. Valid value range: DerivativeTime >= 0.*)
		FilterTime : REAL; (*Filter time constant for the derivative component. Unit: [s]. Valid value range: FilterTime >= 0.*)
		MinIntegrationPartValue : REAL; (*Additional limiter of the integral component between MinIntegrationPartValue and MaxIntegrationPartValue. Valid value range: MinIntegrationPartValue < MaxIntegrationPartValue.*)
		MaxIntegrationPartValue : REAL; (*Additional limiter of the integral component between MinIntegrationPartValue and MaxIntegrationPartValue. Valid value range: MaxIntegrationPartValue > MinIntegrationPartValue.*)
		MinOut : REAL; (*Lower manipulated variable limit. Valid value range: MinOut < MaxOut.*)
		MaxOut : REAL; (*Upper manipulated variable limit. Valid value range: MaxOut > MinOut.*)
	END_STRUCT;
	MTBasicsLevelCtrlParaType : 	STRUCT  (*Level controller parameters.*)
		OutputValue1 : REAL; (*1st Output value.*)
		OutputValue2 : REAL; (*2nd Output value.*)
		OutputValue3 : REAL; (*3rd Output value.*)
		ThresholdLevel1 : REAL; (*Threshold level from OutputValue2 to OutputValue1.*)
		ThresholdLevel2 : REAL; (*Threshold level from OutputValue1 to OutputValue2.*)
		ThresholdLevel3 : REAL; (*Threshold level from OutputValue3 to OutputValue2.*)
		ThresholdLevel4 : REAL; (*Threshold level from OutputValue2 to OutputValue3.*)
	END_STRUCT;
	MTBasicsPWMModeEnum : 
		( (*Pulse mode.*)
		mtPULSE_BEGINNING := 0, (*Pulse at the beginning of a period.*)
		mtPULSE_MIDDLE := 1 (*Pulse in the middle of a period.*)
		);
	MTBasicsStatusEnum : 
		( (*Status information.*)
		mtTUNING_ABORTED_BY_USER := 36250, (*Tuning aborted by user.*)
		mtFIRST_TIME_CONSTANT_ZERO := 36251, (*Operating as P element or PT1 / DT1 element since TimeConstant1 = 0.*)
		mtSECOND_TIME_CONSTANT_ZERO := 36252, (*Operating as P element or PT1 / DT1 element since TimeConstant2 = 0.*)
		mtERR_OUTPUT_LIMIT_INVALID := 36260, (*Error: MinOut, MaxOut invalid.*)
		mtERR_GAIN_INVALID := 36261, (*Error: Gain invalid.*)
		mtERR_INTEGRATION_TIME_NEGATIV := 36262, (*Error: IntegrationTime negative.*)
		mtERR_DERIVATIVE_TIME_NEGATIV := 36263, (*Error: DerivativeTime negative.*)
		mtERR_FILTER_TIME_NEGATIV := 36264, (*Error: FilterTime negative.*)
		mtERR_INTEGRATION_LIMIT_INVALID := 36265, (*Error: MinIntegrationPartValue, MaxIntegrationPartValue invalid.*)
		mtERR_THRESHOLD_NOT_DEFINED := 36266, (*Error: ThresholdLevel1...ThresholdLevel4 undefined.*)
		mtERR_THRESHOLD_INVALID := 36267, (*Error: ThresholdLevel1 = ThresholdLevel4 invalid.*)
		mtERR_OUTPUT_VALUE_NOT_DEFINED := 36268, (*Error: OutputValue1...OutputValue3 undefined.*)
		mtERR_MIN_OUT_NEGATIV := 36269, (*Error: MinOut negative.*)
		mtERR_SAMPLING_INVALID := 36270, (*Error: Oscillation period too short.*)
		mtERR_SET_VALUE_NEGATIV := 36271, (*Error: SetValue negative.*)
		mtERR_FIRST_TIME_CONSTANT_NEG := 36272, (*Error: TimeConstant(1) negative.*)
		mtERR_SECOND_TIME_CONSTANT_NEG := 36273, (*Error: TimeConstant2 negative.*)
		mtERR_GAIN_NEGATIV := 36274, (*Error: Gain negative.*)
		mtERR_MEMORY_ALLOCATION_ERROR := 36275, (*Error: Memory allocation failed.*)
		mtERR_DELAY_TIME_NEGATIV := 36276, (*Error: DelayTime negative.*)
		mtERR_DELAY_TIME_HIGH := 36277, (*Error: DelayTime too high.*)
		mtERR_MAX_POS_SLEW_RATE_NEGATIV := 36278, (*Error: MaxPosSlewRate negative.*)
		mtERR_MAX_NEG_SLEW_RATE_NEGATIV := 36279, (*Error: MaxNegSlewRate negative.*)
		mtERR_DENOM_COEFF_INVALID := 36280, (*Error: Highest denominator coefficient Denominator[Order] = 0.*)
		mtERR_ORDER_NOT_MINIMAL := 36281, (*Error: Order not minimal.*)
		mtERR_ORDER_LIMIT_EXCEEDED := 36282, (*Error: Order invalid.*)
		mtERR_MIN_PULSE_HIGH := 36283, (*Error: MinPulseWidth greater than Period.*)
		mtERR_MIN_PULSE_LOW := 36284, (*Error: MinPulseWidth less than cycle time.*)
		mtERR_PERIOD_LOW := 36285, (*Error: Period less than cycle time.*)
		mtERR_PULSE_WIDTH_LOW := 36286, (*Error: MinPulseWidth less than cycle time.*)
		mtERR_MIN_PAUSE_LOW := 36287, (*Error: MinPause less than cycle time.*)
		mtWARN_OUTPUT_LIMIT_INVALID := 36300, (*Warning: MinOut, MaxOut invalid. Retaining the last valid configuration.*)
		mtWARN_FILTER_TIME_LOW := 36301, (*Warning: FilterTime less than cycle time (DerivativePart = 0).*)
		mtWARN_GAIN_INVALID := 36302, (*Warning: Gain invalid. Retaining the last valid configuration.*)
		mtWARN_INTEGRATION_TIME_NEGATIV := 36303, (*Warning: IntegrationTime invalid. Retaining the last valid configuration.*)
		mtWARN_DERIVATIVE_TIME_NEGATIV := 36304, (*Warning: DerivativeTime invalid. Retaining the last valid configuration.*)
		mtWARN_FILTER_TIME_NEGATIV := 36305, (*Warning: FilterTime invalid. Retaining the last valid configuration.*)
		mtWARN_INTEGRATION_LIMIT_INVALID := 36306, (*Warning: MinIntegrationPartValue, MaxIntegrationPartValue invalid. Retaining the last valid configuration.*)
		mtWARN_THRESHOLD_NOT_DEFINED := 36307, (*Warning: ThresholdLevel1...ThresholdLevel4 undefined. Retaining the last valid configuration.*)
		mtWARN_THRESHOLD_INVALID := 36308, (*Warning: ThresholdLevel1 = ThresholdLevel4 invalid. Retaining the last valid configuration.*)
		mtWARN_OUTPUT_VALUE_NOT_DEFINED := 36309, (*Warning: OutputValue1...OutputValue3 undefined. Retaining the last valid configuration.*)
		mtWARN_MIN_OUT_NEGATIV := 36310, (*Warning: MinOut negative. Retaining the last valid configuration.*)
		mtWARN_SET_VALUE_NEGATIV := 36311, (*Warning: SetValue negative. Retaining the last valid configuration.*)
		mtWARN_GAIN_ZERO := 36312, (*Warning: Gain = 0.*)
		mtWARN_FIRST_TIME_CONSTANT_NEG := 36313, (*Warning: TimeConstant(1) negative. Retaining the last valid configuration.*)
		mtWARN_SECOND_TIME_CONSTANT_NEG := 36314, (*Warning: TimeConstant2 negative. Retaining the last valid configuration.*)
		mtWARN_GAIN_NEGATIV := 36315, (*Warning: Gain negative. Retaining the last valid configuration.*)
		mtWARN_MEMORY_ALLOCATION_EROR := 36316, (*Warning: Memory allocation failed. Retaining the last valid memory.*)
		mtWARN_DELAY_TIME_NEGATIV := 36317, (*Warning: DelayTime negative. Retaining the last valid configuration.*)
		mtWARN_DELAY_TIME_HIGH := 36318, (*Warning: DelayTime too high. Retaining the last valid configuration.*)
		mtWARN_MAX_POS_SLEW_RATE_NEGATIV := 36319, (*Warning: MaxPosSlewRate negative. Retaining the last valid configuration.*)
		mtWARN_MAX_NEG_SLEW_RATE_NEGATIV := 36320, (*Warning: MaxNegSlewRate negative. Retaining the last valid configuration.*)
		mtWARN_DENOM_COEFF_INVALID := 36321, (*Warning: The highest denominator coefficient Denominator[Order] = 0. Retaining the last valid configuration.*)
		mtWARN_ORDER_NOT_MINIMAL := 36322, (*Warning: Order not minimum. Retaining the last valid configuration.*)
		mtWARN_ORDER_LIMIT_EXCEEDED := 36323, (*Warning: Order invalid. Retaining the last valid configuration.*)
		mtWARN_PRESET_INVALID := 36324, (*Warning: Preset for Out output not possible.*)
		mtWARN_MIN_PULSE_HIGH := 36325, (*Warning: MinPulseWidth greater than Period. Retaining the last valid configuration.*)
		mtWARN_MIN_PULSE_LOW := 36326, (*Warning: MinPulseWidth less than cycle time. Retaining the last valid configuration.*)
		mtWARN_PERIOD_LOW := 36327, (*Warning: Period less than cycle time. Retaining the last valid configuration.*)
		mtWARN_PULSE_WIDTH_LOW := 36328, (*Warning: MinPause less than cycle time. Retaining the last valid configuration.*)
		mtWARN_MIN_PAUSE_LOW := 36329 (*Warning: PulseWidth less than cycle time. Retaining the last valid configuration.*)
		);
	MTBasicsPIDInternalType : 	STRUCT  (*Internal variables of function block MTBasicsPID.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		ParameterValid : BOOL; (*Data for internal use.*)
		Parameter : MTBasicsPIDParameterType; (*Data for internal use.*)
		ControlErrorOld : REAL; (*Data for internal use.*)
		OutLimitation : BOOL; (*Data for internal use.*)
		IntegrationPartPresetValue : REAL; (*Data for internal use.*)
		SetIntegrationPart : BOOL; (*Data for internal use.*)
		SetIntegrationPartOld : BOOL; (*Data for internal use.*)
		Update : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	MTBasicsOscTuningInternalType : 	STRUCT  (*Internal variables of function block MTBasicsOscillationTuning.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		Activate3rdPhase : BOOL; (*Activate tuning phase with limited P-controler.*)
		X0 : REAL; (*Output value of the uncontrolled system .*)
		State : USINT; (*State of tuning.*)
		CriticalGain : REAL; (*Critical gain.*)
		OscillationPeriod : REAL; (*Period of oscillation.*)
		NumberOfOscillations : USINT; (*Number of osscilations.*)
		NumberOfPhases : USINT; (*Number of current tuning phase.*)
		MaxRelayOut : REAL; (*Lower limit for output during tuning.*)
		MinRelayOut : REAL; (*Upper limit for output during tuning.*)
		ParameterValid : BOOL; (*Data for internal use.*)
		SetValue : REAL; (*Data for internal use.*)
		AverageOutValue : REAL; (*Data for internal use.*)
		MaxActValueTime : ARRAY[0..3]OF REAL; (*Data for internal use.*)
		MinActValueTime : ARRAY[0..3]OF REAL; (*Data for internal use.*)
		MaxActValue : ARRAY[0..3]OF REAL; (*Data for internal use.*)
		MinActValue : ARRAY[0..3]OF REAL; (*Data for internal use.*)
		OutNegEdgeTime : ARRAY[0..3]OF REAL; (*Data for internal use.*)
		OutPosEdgeTime : ARRAY[0..3]OF REAL; (*Data for internal use.*)
		TuningTime : REAL; (*Data for internal use.*)
		StartingActValue : REAL; (*Data for internal use.*)
		ControlError : REAL; (*Data for internal use.*)
		ActValueAverageAmplitude : REAL; (*Data for internal use.*)
		AverageActValue : REAL; (*Data for internal use.*)
		AverageMaxActValue : REAL; (*Data for internal use.*)
		AverageMinActValue : REAL; (*Data for internal use.*)
		AmplitudeRatio : REAL; (*Data for internal use.*)
		ControlErrorOldFalling : REAL; (*Data for internal use.*)
		ControlErrorOldRising : REAL; (*Data for internal use.*)
		DeltaOut : REAL; (*Data for internal use.*)
		EffectiveDirection : SINT; (*Data for internal use.*)
		StartOld : BOOL; (*Data for internal use.*)
		ControlErrorSetValueCross : REAL; (*Data for internal use.*)
		RisingProportionalController : BOOL; (*Data for internal use.*)
		FallingProportionalController : BOOL; (*Data for internal use.*)
		SaturatedControlError : REAL; (*Data for internal use.*)
		ControlErrorOld : REAL; (*Data for internal use.*)
		Update : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
		MinOscillationAmplitude : REAL; (*Data for internal use.*)
		MinOut : REAL; (*Data for internal use.*)
		MaxOut : REAL; (*Data for internal use.*)
		TemporaryQuality : REAL; (*Data for internal use.*)
		TemporaryDerivativeTime : REAL; (*Data for internal use.*)
		TemporaryIntegrationTime : REAL; (*Data for internal use.*)
		TemporaryGain : REAL; (*Data for internal use.*)
	END_STRUCT;
	MTBasicsLevelCtrlInternalType : 	STRUCT  (*Internal variables of function block MTBasicsLevelController.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		ParameterValid : BOOL; (*Data for internal use.*)
		Parameter : MTBasicsLevelCtrlParaType; (*Data for internal use.*)
		State : USINT; (*Data for internal use.*)
		Update : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	MTBasicsPT1InternalType : 	STRUCT  (*Internal variables of function block MTBasicsPT1.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		ParameterValid : BOOL; (*Data for internal use.*)
		Gain : REAL; (*Data for internal use.*)
		TimeConstant : REAL; (*Data for internal use.*)
		BVector : ARRAY[0..1]OF REAL; (*Data for internal use.*)
		AVector : ARRAY[0..1]OF REAL; (*Data for internal use.*)
		XVector : REAL; (*Data for internal use.*)
		OutPresetValue : REAL; (*Data for internal use.*)
		SetOut : BOOL; (*Data for internal use.*)
		SetOutOld : BOOL; (*Data for internal use.*)
		Update : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	MTBasicsPT2InternalType : 	STRUCT  (*Internal variables of function block MTBasicsPT2.*)
		CycleTime : REAL; (*Task cycle time. Unit: [µs].*)
		ParameterValid : BOOL; (*Data for internal use.*)
		Gain : REAL; (*Data for internal use.*)
		TimeConstant1 : REAL; (*Data for internal use.*)
		TimeConstant2 : REAL; (*Data for internal use.*)
		BVector : ARRAY[0..2]OF REAL; (*Data for internal use.*)
		AVector : ARRAY[0..2]OF REAL; (*Data for internal use.*)
		XVector : ARRAY[0..1]OF REAL; (*Data for internal use.*)
		OutPresetValue : REAL; (*Data for internal use.*)
		SetOut : BOOL; (*Data for internal use.*)
		SetOutOld : BOOL; (*Data for internal use.*)
		Update : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	MTBasicsDT1InternalType : 	STRUCT  (*Internal variables of function block MTBasicsDT1.*)
		CycleTime : REAL; (*Task cycle time. Unit: [µs].*)
		ParameterValid : BOOL; (*Data for internal use.*)
		Gain : REAL; (*Data for internal use.*)
		BVector : ARRAY[0..1]OF REAL; (*Data for internal use.*)
		AVector : ARRAY[0..1]OF REAL; (*Data for internal use.*)
		XVector : REAL; (*Data for internal use.*)
		Update : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	MTBasicsDT2InternalType : 	STRUCT  (*Internal variables of function block MTBasicsDT2.*)
		CycleTime : REAL; (*Task cycle time. Unit: [µs].*)
		ParameterValid : BOOL; (*Data for internal use.*)
		Gain : REAL; (*Data for internal use.*)
		TimeConstant1 : REAL; (*Data for internal use.*)
		TimeConstant2 : REAL; (*Data for internal use.*)
		BVector : ARRAY[0..2]OF REAL; (*Data for internal use.*)
		AVector : ARRAY[0..2]OF REAL; (*Data for internal use.*)
		XVector : ARRAY[0..1]OF REAL; (*Data for internal use.*)
		Update : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	MTBasicsIntegratorInternalType : 	STRUCT  (*Internal variables of function block MTBasicsIntegrator.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		ParameterValid : BOOL; (*Data for internal use.*)
		BVector : ARRAY[0..1]OF REAL; (*Data for internal use.*)
		AVector : ARRAY[0..1]OF REAL; (*Data for internal use.*)
		XVector : REAL; (*Data for internal use.*)
		OutPresetValue : REAL; (*Data for internal use.*)
		SetOut : BOOL; (*Data for internal use.*)
		SetOutOld : BOOL; (*Data for internal use.*)
		Update : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	MTBasicsTimeDelayInternalType : 	STRUCT  (*Internal variables of function block MTBasicsTimeDelay.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		ParameterValid : BOOL; (*Data for internal use.*)
		DelayTimeAct : REAL; (*Data for internal use.*)
		MaxNumberOfBufferElements : UDINT; (*Data for internal use.*)
		ActNumberOfBufferElements : UDINT; (*Data for internal use.*)
		DelayCounter : UDINT; (*Data for internal use.*)
		ActBufferIndex : UDINT; (*Data for internal use.*)
		BufferPointer : REFERENCE TO REAL; (*Data for internal use.*)
		OutPresetValue : REAL; (*Data for internal use.*)
		SetOut : BOOL; (*Data for internal use.*)
		SetOutOld : BOOL; (*Data for internal use.*)
		Update : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	MTBasicsLimiterInternalType : 	STRUCT  (*Internal variables of function block MTBasicsLimiter.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		ParameterValid : BOOL; (*Data for internal use.*)
		MaxOut : REAL; (*Data for internal use.*)
		MinOut : REAL; (*Data for internal use.*)
		MaxPosSlewRate : REAL; (*Data for internal use.*)
		MaxNegSlewRate : REAL; (*Data for internal use.*)
		Out : REAL; (*Data for internal use.*)
		OutOld : REAL; (*Data for internal use.*)
		UpperOutLimit : REAL; (*Data for internal use.*)
		LowerOutLimit : REAL; (*Data for internal use.*)
		SetOutOld : BOOL; (*Data for internal use.*)
		Update : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	MTBasicsTransFcnInternalType : 	STRUCT  (*Internal variables of function block MTBasicsTransferFcn.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		ParameterValid : BOOL; (*Data for internal use.*)
		Order : USINT; (*Data for internal use.*)
		PresetOK : BOOL; (*Data for internal use.*)
		PresetCoefficients : LREAL; (*Data for internal use.*)
		BVector : ARRAY[0..5]OF LREAL; (*Data for internal use.*)
		AVector : ARRAY[0..5]OF LREAL; (*Data for internal use.*)
		XVector : ARRAY[0..4]OF LREAL; (*Data for internal use.*)
		OutPresetValue : REAL; (*Data for internal use.*)
		SetOut : BOOL; (*Data for internal use.*)
		SetOutOld : BOOL; (*Data for internal use.*)
		Update : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	MTBasicsDiscrTransFcnInternType : 	STRUCT  (*Internal variables of function block MTBasicsDiscreteTransferFcn.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		ParameterValid : BOOL; (*Data for internal use.*)
		Order : USINT; (*Data for internal use.*)
		PresetOK : BOOL; (*Data for internal use.*)
		PresetCoefficients : LREAL; (*Data for internal use.*)
		BVector : ARRAY[0..5]OF LREAL; (*Data for internal use.*)
		AVector : ARRAY[0..5]OF LREAL; (*Data for internal use.*)
		XVector : ARRAY[0..4]OF LREAL; (*Data for internal use.*)
		OutPresetValue : REAL; (*Data for internal use.*)
		SetOut : BOOL; (*Data for internal use.*)
		SetOutOld : BOOL; (*Data for internal use.*)
		Update : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	MTBasicsPWMInternalType : 	STRUCT  (*Internal variables of function block MTBasicsPWM.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		OnTime : REAL; (*Data for internal use.*)
		OffTime : REAL; (*Data for internal use.*)
		ParameterValid : BOOL; (*Data for internal use.*)
		Mode : USINT; (*Data for internal use.*)
		Period : REAL; (*Data for internal use.*)
		MinPulseWidth : REAL; (*Data for internal use.*)
		PeriodCounter : REAL; (*Data for internal use.*)
		OnTimeCounter : REAL; (*Data for internal use.*)
		TimeCorrection : REAL; (*Data for internal use.*)
		Update : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
	MTBasicsPFMInternalType : 	STRUCT  (*Internal variables of function block MTBasicsPFM.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		ParameterValid : BOOL; (*Data for internal use.*)
		In : REAL; (*Data for internal use.*)
		PulseWidth : REAL; (*Data for internal use.*)
		MinPause : REAL; (*Data for internal use.*)
		Area : REAL; (*Data for internal use.*)
		AreaC : REAL; (*Data for internal use.*)
		OffTime : REAL; (*Data for internal use.*)
		OnTime : REAL; (*Data for internal use.*)
		Update : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		Bootkey : UDINT; (*Data for internal use.*)
	END_STRUCT;
END_TYPE
