#ifndef _LIBRARIES_WBRSERVICES_TIMERSERVICES_MSTIMESVC_DEFAULT_1663349377
#define _LIBRARIES_WBRSERVICES_TIMERSERVICES_MSTIMESVC_DEFAULT_1663349377
#include "../AsDefault.h"
#include <bur/plctypes.h>
#include <bur/plc.h>
#endif
